        MODULE MTREE

        IMPLICIT NONE
        
        SAVE

        INTEGER,ALLOCATABLE, DIMENSION(:,:) :: DMLIP
        INTEGER,ALLOCATABLE, DIMENSION(:,:) :: DMLIR
        REAL*4,ALLOCATABLE, DIMENSION(:,:) :: NEW_MASAP

        INTEGER,ALLOCATABLE, DIMENSION(:,:,:) :: NHOST
        INTEGER,ALLOCATABLE, DIMENSION(:,:,:,:) :: HHOST

        REAL*4,ALLOCATABLE, DIMENSION(:,:,:) :: RATIO
        INTEGER,ALLOCATABLE, DIMENSION(:,:) :: NDAD
        INTEGER,ALLOCATABLE, DIMENSION(:,:,:) :: DAD

        END MODULE MTREE        
