      MODULE PARTICLES

       IMPLICIT NONE

       SAVE

       INTEGER PARTI, PARTI_PPH

       REAL,ALLOCATABLE::RXPA(:),RYPA(:),RZPA(:)
       REAL,ALLOCATABLE::U2DM(:),U3DM(:),U4DM(:)
       REAL,ALLOCATABLE::MASAP(:)
       INTEGER,ALLOCATABLE::ORIPA(:),PARTICLES_PER_HALO(:)

      END MODULE PARTICLES
